version: '3'

services:
    postgres:
        container_name: luigi_db
        image: postgres:10
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=luigid
            - POSTGRES_USER=luigid
            - POSTGRES_HOST_AUTH_METHOD=trust
    luigi_service:
        container_name: luigi_service
        build: .
        ports:
            - 9091:9091
        volumes:
            - '.:/app'
        depends_on:
            - postgres
            - redis
    redis:
        image: redis
        ports:
            - 6379:6379

# docker exec -it luigi_db psql -d luigid -U luigid

